version: 2.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node14.12.0-chrome87-ff83
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm ci
      - run:
          name: Run tests
          command: |
            npx cypress run